//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCLEAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poruka
    {
        public int idPoruke { get; set; }
        public string poruka1 { get; set; }
        public System.DateTime datumObjave { get; set; }
    }
}
